version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: crypto_monitoring
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # LocalStack for AWS services emulation
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - TMPDIR=/tmp/localstack_tmp
    volumes:
      - "${TMPDIR:-/tmp}/localstack_tmp:/tmp/localstack_tmp"
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  postgres-data: 