version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: crypto_monitoring
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # Market Checker Service
  market_checker:
    image: market_checker
    container_name: market_checker
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/crypto_monitoring
      - PYTH_ENDPOINT=https://hermes.pyth.network
      - WEB3_PROVIDER_URL=${WEB3_PROVIDER_URL}
      - ORACLE_CONTRACT_ADDRESS=${ORACLE_CONTRACT_ADDRESS}
      - MARKET_FACTORY_CONTRACT_ADDRESS=${MARKET_FACTORY_CONTRACT_ADDRESS}
      - PYTH_CONTRACT_ADDRESS=${PYTH_CONTRACT_ADDRESS}
      - MATCHING_ENGINE_BASE_URL=${MATCHING_ENGINE_BASE_URL}
      - PRIVATE_KEY_0=${PRIVATE_KEY_0}
      - PRIVATE_KEY_1=${PRIVATE_KEY_1}
      - PRIVATE_KEY_2=${PRIVATE_KEY_2}
      - PRIVATE_KEY_3=${PRIVATE_KEY_3}
      - PRIVATE_KEY_4=${PRIVATE_KEY_4}
      - PRIVATE_KEY_5=${PRIVATE_KEY_5}
      - PRIVATE_KEY_6=${PRIVATE_KEY_6}
      - PRIVATE_KEY_7=${PRIVATE_KEY_7}
      - PRIVATE_KEY_8=${PRIVATE_KEY_8}
      - PRIVATE_KEY_9=${PRIVATE_KEY_9}
    depends_on:
      - postgres

volumes:
  postgres-data: 